- include: packages.yml
- include: lighttpd.yml

- name: Set hostname
  become: true
  hostname: name={{ansible_hostname}}
  
- name: Add modules to /etc/modules
  become: true
  lineinfile: dest=/etc/modules state=present line="{{item}}"
  with_items:
    - "w1-gpio"
    - "w1-therm"

- name: Add modules to /boot/config.txt
  become: true
  lineinfile: dest=/boot/config.txt state=present line="{{item}}"
  with_items:
    - "dtoverlay=w1-gpio"


#--- user aliases and stuff
- name: Copy .aliases
  copy: src=dot_aliases dest=/home/pi/.aliases

- name: Copy .profile
  copy: src=dot_bash_profile dest=/home/pi/.bash_profile


#- name: Directory /var/lib/rpi-sous-vide/tmp
#  become: true
#  file: state=directory dest=/var/lib/rpi-sous-vide/tmp owner=pi group=pi mode=0755
  
- name: tmpfs /var/lib/rpi-sous-vide/tmp
  become: true
  mount: name=/var/lib/rpi-sous-vide/tmp fstype=tmpfs src=tmpfs opts="defaults,noatime,nosuid,size=30m" state=mounted
  tags: mount
  
  
#line="tmpfs    /var/lib/rpi-sous-vide/tmp    tmpfs    defaults,noatime,nosuid,size=30m    0 0" dest=/etc/fstab